package com.bootcamp2020.ecommerceProject.enums;

public enum FromStatus {

    REFUND_COMPLETED,
    REFUND_INITIATED,
    PICK_UP_COMPLETED,
    PICK_UP_INITIATED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_REQUESTED,
    DELIVERED,
    ORDER_SHIPPED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    CANCELLED,
    ORDER_PLACED
}
